import type { NodeConfig, ParamSpec, Socket, SocketType } from '../types/data';
import { EXEC } from './exec';

const s = (id: string, name: string, type: SocketType): Socket => ({ id, name, type });

export const nodeConfigs: NodeConfig[] = [
  // ================= 组输入节点 =================
  {
    id: 'table_input',
    label: '表格输入',
    category: 'input',
    description: '输入表格数据:支持内置预设(火山图/销售/鸢尾花/物理曲线),或粘贴 CSV/TSV,或从文件导入。',
    inputs: [],
    outputs: [s('out0', '表格', 'table')],
    params: [
      { key: 'preset', label: '数据预设', type: 'select', default: 'volcano', options: [
        { value: 'volcano', label: '火山图数据(基因表达)' },
        { value: 'sales', label: '销售数据' },
        { value: 'iris', label: '鸢尾花数据' },
        { value: 'phys', label: '物理曲线(带噪声)' },
      ] },
      { key: 'mode', label: '数据来源', type: 'select', default: 'preset', options: [
        { value: 'preset', label: '使用预设' },
        { value: 'manual', label: '手动数据' },
      ] },
      { key: 'delimiter', label: '分隔符', type: 'select', default: 'csv', options: [
        { value: 'csv', label: '逗号 ,' },
        { value: 'tsv', label: '制表符 Tab' },
      ] },
      { key: 'dataText', label: '数据文本', type: 'textarea', default: '', placeholder: '每行一条记录,首行可为列名\nx,y\n1,2.5\n2,3.1\n...' },
      { key: 'import', label: '从 CSV/Excel 文件导入', type: 'button', default: null, action: 'import-csv' },
    ],
    exec: EXEC.table_input,
  },
  {
    id: 'axis_input',
    label: '坐标系输入',
    category: 'input',
    description: '定义一个坐标系:维度(2D/3D)、各轴像素大小、X/Y 起止数字、坐标轴定位方式(以原点为中心/总贴左边沿)与边框开关。刻度数量按像素密度自动确定并标注数字。',
    inputs: [],
    outputs: [s('out0', '坐标系', 'axes')],
    params: [
      { key: 'name', label: '坐标系名称', type: 'text', default: '坐标系' },
      { key: 'dim', label: '维度', type: 'select', default: '3d', options: [
        { value: '3d', label: '三维 (X, Y, Z)' },
        { value: '2d', label: '二维 (X, Y)' },
      ] },
      { key: 'xLen', label: 'X 像素大小', type: 'number', default: 1600, step: 50, min: 100 },
      { key: 'yLen', label: 'Y 像素大小', type: 'number', default: 1000, step: 50, min: 100 },
      { key: 'zLen', label: 'Z 像素大小(3D)', type: 'number', default: 800, step: 50, min: 100 },
      { key: 'xStart', label: 'X 起始数字', type: 'number', default: 0, step: 0.1 },
      { key: 'xEnd', label: 'X 结束数字', type: 'number', default: 10, step: 0.1 },
      { key: 'yStart', label: 'Y 起始数字', type: 'number', default: 0, step: 0.1 },
      { key: 'yEnd', label: 'Y 结束数字', type: 'number', default: 10, step: 0.1 },
      { key: 'zStart', label: 'Z 起始数字(3D)', type: 'number', default: -5, step: 0.1 },
      { key: 'zEnd', label: 'Z 结束数字(3D)', type: 'number', default: 5, step: 0.1 },
      { key: 'axisOrigin', label: '坐标轴位置', type: 'select', default: 'origin', options: [
        { value: 'origin', label: '以原点为中心(有原点过原点,否则贴边)' },
        { value: 'left', label: '总贴左边沿' },
      ] },
      { key: 'showBorder', label: '显示边界边框', type: 'boolean', default: true },
      { key: 'grid', label: '显示网格', type: 'boolean', default: true },
      { key: 'labelX', label: 'X 轴标签', type: 'text', default: 'X' },
      { key: 'labelY', label: 'Y 轴标签', type: 'text', default: 'Y' },
      { key: 'labelZ', label: 'Z 轴标签(3D)', type: 'text', default: 'Z' },
    ],
    exec: EXEC.axis_input,
  },
  {
    id: 'line_input',
    label: '线输入',
    category: 'input',
    description: '输入一条曲线/折线:参数方程生成或手动输入点列。',
    inputs: [],
    outputs: [s('out0', '曲线', 'series')],
    params: [
      { key: 'name', label: '线名称', type: 'text', default: '线' },
      { key: 'mode', label: '模式', type: 'select', default: 'parametric', options: [
        { value: 'parametric', label: '参数方程' },
        { value: 'points', label: '手动点列' },
      ] },
      { key: 'fx', label: 'x = f(t)', type: 'text', default: 'x' },
      { key: 'fy', label: 'y = f(t)', type: 'text', default: 'sin(x)' },
      { key: 'start', label: '起始', type: 'number', default: 0, step: 0.1 },
      { key: 'end', label: '结束', type: 'number', default: 10, step: 0.1 },
      { key: 'count', label: '采样数', type: 'number', default: 200, step: 1, min: 2 },
      { key: 'pointsText', label: '点列(每行 x,y)', type: 'textarea', default: '0,0\n1,2\n2,1\n3,5' },
    ],
    exec: EXEC.line_input,
  },
  {
    id: 'face_input',
    label: '面输入',
    category: 'input',
    description: '输入网格面(三角形网格):平面、球体或环面。',
    inputs: [],
    outputs: [s('out0', '面/网格', 'mesh')],
    params: [
      { key: 'name', label: '面名称', type: 'text', default: '面' },
      { key: 'geometry', label: '几何体', type: 'select', default: 'sphere', options: [
        { value: 'plane', label: '平面' },
        { value: 'sphere', label: '球体' },
        { value: 'torus', label: '环面' },
      ] },
      { key: 'nu', label: 'U 分段', type: 'number', default: 24, step: 1, min: 2 },
      { key: 'nv', label: 'V 分段', type: 'number', default: 24, step: 1, min: 2 },
      { key: 'radius', label: '半径/尺寸', type: 'number', default: 2, step: 0.1 },
      { key: 'radius2', label: '内半径(环面)', type: 'number', default: 0.8, step: 0.1 },
    ],
    exec: EXEC.face_input,
  },
  {
    id: 'grid_input',
    label: '网格数据输入',
    category: 'input',
    description: '输入规则网格数据 z = f(x,y),用于曲面/热力图可视化。',
    inputs: [],
    outputs: [s('out0', '网格数据', 'grid')],
    params: [
      { key: 'name', label: '网格名称', type: 'text', default: '网格' },
      { key: 'formula', label: 'z = f(x,y)', type: 'text', default: 'sin(sqrt(x*x+y*y))', help: '支持 x、y 变量与常用函数' },
      { key: 'xmin', label: 'X 最小', type: 'number', default: -4, step: 0.1 },
      { key: 'xmax', label: 'X 最大', type: 'number', default: 4, step: 0.1 },
      { key: 'ymin', label: 'Y 最小', type: 'number', default: -4, step: 0.1 },
      { key: 'ymax', label: 'Y 最大', type: 'number', default: 4, step: 0.1 },
      { key: 'nx', label: 'X 网格数', type: 'number', default: 40, step: 1, min: 2 },
      { key: 'ny', label: 'Y 网格数', type: 'number', default: 40, step: 1, min: 2 },
    ],
    exec: EXEC.grid_input,
  },
  {
    id: 'scatter_input',
    label: '聚合点输入',
    category: 'input',
    description: '逐个添加数据点:每个点可独立设置 X/Y 坐标、大小、形状与颜色。初始只有一个加号,可不断添加。',
    inputs: [],
    outputs: [s('out0', '散点', 'scatter')],
    params: [
      { key: 'name', label: '名称', type: 'text', default: '聚合点' },
      { key: 'points', label: '聚合点列表', type: 'points', default: [], help: '点击"＋ 添加点"逐点添加;每个点有 x/y 坐标、大小、形状、颜色' },
    ],
    exec: EXEC.scatter_input,
  },
  {
    id: 'series_input',
    label: '曲线输入',
    category: 'input',
    description: '输入一条曲线:二次曲线、正弦+噪声或随机游走。',
    inputs: [],
    outputs: [s('out0', '曲线', 'series')],
    params: [
      { key: 'preset', label: '数据预设', type: 'select', default: 'quadratic', options: [
        { value: 'quadratic', label: '二次曲线(带噪声)' },
        { value: 'sin-noise', label: '正弦+噪声' },
        { value: 'random-walk', label: '随机游走' },
      ] },
    ],
    exec: EXEC.series_input,
  },
  {
    id: 'func_curve',
    label: '函数曲线',
    category: 'input',
    description: '输入函数表达式 y=f(x),输出按区间采样生成的曲线。支持 x、sin/cos/tan/exp/log/sqrt/abs、^、pi、e。',
    inputs: [],
    outputs: [s('out0', '曲线', 'series')],
    params: [
      { key: 'name', label: '曲线名称', type: 'text', default: '函数曲线' },
      { key: 'expression', label: 'y = f(x)', type: 'text', default: 'sin(x)', help: '支持 x、sin/cos/tan/exp/log/sqrt/abs、^、pi、e' },
      { key: 'xMin', label: 'X 起始', type: 'number', default: 0, step: 0.1 },
      { key: 'xMax', label: 'X 结束', type: 'number', default: 10, step: 0.1 },
      { key: 'samples', label: '采样数', type: 'number', default: 200, step: 1, min: 2 },
    ],
    exec: EXEC.func_curve,
  },

  // ================= 数据初步节点 =================
  {
    id: 'clean',
    label: '数据清洗',
    category: 'clean',
    description: '清理表格:缺失值填充(零/均值/线性插值)、删除含缺失的行、去除重复行。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '清洗后表格', 'table')],
    params: [
      { key: 'fillMissing', label: '缺失值填充', type: 'select', default: 'none', options: [
        { value: 'none', label: '不填充' },
        { value: 'zero', label: '填充 0' },
        { value: 'mean', label: '填充均值' },
        { value: 'interp', label: '线性插值' },
      ] },
      { key: 'dropMissing', label: '删除含缺失的行', type: 'boolean', default: false },
      { key: 'dedupe', label: '去除重复行', type: 'boolean', default: false },
    ],
    exec: EXEC.clean,
  },
  {
    id: 'normalize',
    label: '标准化',
    category: 'clean',
    description: '对数值列做 min-max 归一化或 z-score 标准化。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '标准化表格', 'table')],
    params: [
      { key: 'method', label: '方法', type: 'select', default: 'minmax', options: [
        { value: 'minmax', label: 'min-max 归一化' },
        { value: 'zscore', label: 'z-score 标准化' },
      ] },
      { key: 'columns', label: '列(留空=全部数值列)', type: 'text', default: '', placeholder: '如:log2FC,pvalue 或 1,2' },
    ],
    exec: EXEC.normalize,
  },
  {
    id: 'filter',
    label: '条件筛选',
    category: 'clean',
    description: '按某列数值区间筛选行(可剔除离群点)。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '筛选后表格', 'table')],
    params: [
      { key: 'column', label: '筛选列', type: 'text', default: '' },
      { key: 'min', label: '最小值(留空不限)', type: 'text', default: '' },
      { key: 'max', label: '最大值(留空不限)', type: 'text', default: '' },
    ],
    exec: EXEC.filter,
  },
  {
    id: 'sample',
    label: '数据抽样',
    category: 'clean',
    description: '对表格抽样:取前 N 行、隔行抽样或随机抽样。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '抽样表格', 'table')],
    params: [
      { key: 'method', label: '方法', type: 'select', default: 'first', options: [
        { value: 'first', label: '取前 N 行' },
        { value: 'every', label: '隔行抽样' },
        { value: 'random', label: '随机抽样' },
      ] },
      { key: 'count', label: '行数(N)', type: 'number', default: 20, step: 1, min: 0 },
      { key: 'step', label: '步长(隔行)', type: 'number', default: 2, step: 1, min: 1 },
    ],
    exec: EXEC.sample,
  },

  // ================= 数据运算节点 =================
  {
    id: 'derivative',
    label: '数值求导',
    category: 'compute',
    description: '对曲线做数值求导(中心差分),输出导数曲线。',
    inputs: [s('in0', '曲线', 'series')],
    outputs: [s('out0', '导数曲线', 'series')],
    params: [{ key: 'name', label: '输出名称', type: 'text', default: '导数' }],
    exec: EXEC.derivative,
  },
  {
    id: 'integral',
    label: '数值积分',
    category: 'compute',
    description: '对曲线做梯形法累积积分,输出积分曲线。',
    inputs: [s('in0', '曲线', 'series')],
    outputs: [s('out0', '积分曲线', 'series')],
    params: [{ key: 'name', label: '输出名称', type: 'text', default: '积分' }],
    exec: EXEC.integral,
  },
  {
    id: 'fit',
    label: '曲线拟合',
    category: 'compute',
    description: '对散点做多项式(1~3 阶)或指数拟合,输出拟合曲线与系数表。',
    inputs: [s('in0', '散点', 'scatter')],
    outputs: [s('out0', '拟合曲线', 'series'), s('out1', '系数表', 'table')],
    params: [
      { key: 'name', label: '输出名称', type: 'text', default: '拟合曲线' },
      { key: 'method', label: '方法', type: 'select', default: 'linear', options: [
        { value: 'linear', label: '线性拟合' },
        { value: 'poly', label: '多项式拟合' },
        { value: 'exponential', label: '指数拟合' },
      ] },
      { key: 'degree', label: '多项式阶数', type: 'number', default: 2, step: 1, min: 1, max: 6 },
    ],
    exec: EXEC.fit,
  },
  {
    id: 'smooth',
    label: '平滑',
    category: 'compute',
    description: '滑动平均平滑曲线。',
    inputs: [s('in0', '曲线', 'series')],
    outputs: [s('out0', '平滑曲线', 'series')],
    params: [
      { key: 'name', label: '输出名称', type: 'text', default: '平滑曲线' },
      { key: 'window', label: '窗口半径', type: 'number', default: 5, step: 1, min: 1 },
    ],
    exec: EXEC.smooth,
  },
  {
    id: 'formula',
    label: '公式运算',
    category: 'compute',
    description: '对曲线逐点计算 y\' = f(x),x 为原 x,y 为原 y。',
    inputs: [s('in0', '曲线', 'series')],
    outputs: [s('out0', '结果曲线', 'series')],
    params: [
      { key: 'name', label: '输出名称', type: 'text', default: '结果' },
      { key: 'expression', label: '表达式 f(x)', type: 'text', default: '2*x + 1', help: '支持 x、y、sin/cos/exp/log/sqrt、^' },
    ],
    exec: EXEC.formula,
  },

  // ================= 数据转化节点 =================
  {
    id: 'extract_columns',
    label: '提取列',
    category: 'transform',
    description: '按列名或 1 起始索引提取表格列。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '新表格', 'table')],
    params: [
      { key: 'columns', label: '列(逗号分隔)', type: 'text', default: '', placeholder: '如:log2FC,pvalue 或 2,4' },
    ],
    exec: EXEC.extract_columns,
  },
  {
    id: 'extract_rows',
    label: '提取行',
    category: 'transform',
    description: '按行区间与步长提取表格子集。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '新表格', 'table')],
    params: [
      { key: 'start', label: '起始行(0 起始)', type: 'number', default: 0, step: 1, min: 0 },
      { key: 'end', label: '结束行', type: 'number', default: 99, step: 1, min: 0 },
      { key: 'step', label: '步长', type: 'number', default: 1, step: 1, min: 1 },
    ],
    exec: EXEC.extract_rows,
  },
  {
    id: 'table_to_scatter',
    label: '表格转散点',
    category: 'transform',
    description: '选取表格中两(三)列生成散点,并携带点形状/大小/颜色。点大小与点颜色可暴露为输入口,接入数据列后每个点的大小/颜色与该行数值成正比。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '散点', 'scatter')],
    params: [
      { key: 'name', label: '名称', type: 'text', default: '散点' },
      { key: 'xCol', label: 'X 列', type: 'text', default: '' },
      { key: 'yCol', label: 'Y 列', type: 'text', default: '' },
      { key: 'zCol', label: 'Z 列(可选,三维)', type: 'text', default: '' },
      { key: 'pointShape', label: '点形状', type: 'select', default: 'circle', options: [
        { value: 'circle', label: '圆形' },
        { value: 'square', label: '方形' },
        { value: 'diamond', label: '菱形' },
        { value: 'triangle', label: '三角形' },
      ] },
      { key: 'pointSize', label: '点大小', type: 'range', default: 4, min: 1, max: 16, step: 0.5, expose: true },
      { key: 'pointColor', label: '点颜色', type: 'color', default: '#1f77b4', expose: true },
    ],
    exec: EXEC.table_to_scatter,
  },
  {
    id: 'table_to_series',
    label: '表格转曲线',
    category: 'transform',
    description: '选取表格中两列生成曲线,并携带线形状/粗细/颜色。线宽与线颜色可暴露为输入口,接入数据列后逐段变化。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '曲线', 'series')],
    params: [
      { key: 'name', label: '名称', type: 'text', default: '曲线' },
      { key: 'xCol', label: 'X 列', type: 'text', default: '' },
      { key: 'yCol', label: 'Y 列', type: 'text', default: '' },
      { key: 'lineStyle', label: '线形状', type: 'select', default: 'solid', options: [
        { value: 'solid', label: '实线' },
        { value: 'dashed', label: '虚线' },
      ] },
      { key: 'lineWidth', label: '线宽', type: 'range', default: 2, min: 0.5, max: 10, step: 0.5, expose: true },
      { key: 'lineColor', label: '线颜色', type: 'color', default: '#ff7f0e', expose: true },
    ],
    exec: EXEC.table_to_series,
  },
  {
    id: 'table_to_distribution',
    label: '表格转分布',
    category: 'transform',
    description: '将表格某数值列转化为直方图分布。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [s('out0', '分布', 'distribution')],
    params: [
      { key: 'name', label: '名称', type: 'text', default: '分布' },
      { key: 'column', label: '数据列', type: 'text', default: '' },
      { key: 'bins', label: '分组数', type: 'number', default: 20, step: 1, min: 2 },
    ],
    exec: EXEC.table_to_distribution,
  },
  {
    id: 'series_to_scatter',
    label: '曲线转散点',
    category: 'transform',
    description: '将曲线数据转化为散点数据,并携带点形状/大小/颜色。点大小与点颜色可暴露为输入口,接入数据列后逐点变化。',
    inputs: [s('in0', '曲线', 'series')],
    outputs: [s('out0', '散点', 'scatter')],
    params: [
      { key: 'name', label: '名称', type: 'text', default: '散点' },
      { key: 'pointShape', label: '点形状', type: 'select', default: 'circle', options: [
        { value: 'circle', label: '圆形' },
        { value: 'square', label: '方形' },
        { value: 'diamond', label: '菱形' },
        { value: 'triangle', label: '三角形' },
      ] },
      { key: 'pointSize', label: '点大小', type: 'range', default: 4, min: 1, max: 16, step: 0.5, expose: true },
      { key: 'pointColor', label: '点颜色', type: 'color', default: '#1f77b4', expose: true },
    ],
    exec: EXEC.series_to_scatter,
  },

  // ================= 数据可视化节点(每个图表独立节点,按需暴露接口) =================
  {
    id: 'viz_scatter',
    label: '散点图',
    category: 'visualize',
    description: '以表格两列绘制散点图;也可直接接入散点/曲线数据可视化。',
    inputs: [
      s('in0', '表格', 'table'),
      s('in1', '散点(可选)', 'scatter'),
      s('in2', '曲线(可选)', 'series'),
    ],
    outputs: [],
    params: [
      { key: 'xCol', label: 'X 列', type: 'text', default: '', help: '留空自动选择' },
      { key: 'yCol', label: 'Y 列', type: 'text', default: '', help: '留空自动选择' },
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_line',
    label: '折线图',
    category: 'visualize',
    description: '以表格一列(或多条曲线)绘制折线图。',
    inputs: [
      s('in0', '表格', 'table'),
      s('in1', '曲线(可选)', 'series'),
    ],
    outputs: [],
    params: [
      { key: 'xCol', label: 'X 列', type: 'text', default: '', help: '留空自动选择' },
      { key: 'yCol', label: 'Y 列', type: 'text', default: '', help: '留空自动选择' },
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_bar',
    label: '柱状图',
    category: 'visualize',
    description: '以表格两列绘制柱状图(分类 + 数值)。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [],
    params: [
      { key: 'xCol', label: 'X 列', type: 'text', default: '', help: '留空自动选择' },
      { key: 'yCol', label: 'Y 列', type: 'text', default: '', help: '留空自动选择' },
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_volcano',
    label: '火山图',
    category: 'visualize',
    description: '差异分析火山图:以 log2FC 与 p 值两列绘制,自动标注显著点。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [],
    params: [
      { key: 'fcCol', label: 'log2FC 列', type: 'text', default: 'log2FC' },
      { key: 'pCol', label: 'p 值列', type: 'text', default: 'pvalue' },
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_heatmap',
    label: '热力图',
    category: 'visualize',
    description: '数值矩阵热力图:取表格前 10 个数值列,行数自动降采样以保证流畅。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [],
    params: [
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_box',
    label: '箱线图',
    category: 'visualize',
    description: '多组数值分布箱线图:每个数值列一个箱体。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [],
    params: [
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_violin',
    label: '小提琴图',
    category: 'visualize',
    description: '多组数值分布小提琴图(核密度估计):每个数值列一个小提琴。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [],
    params: [
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_sankey',
    label: '桑基图',
    category: 'visualize',
    description: '流程/流量桑基图:按源列→目标列聚合权重。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [],
    params: [
      { key: 'sourceCol', label: '源列', type: 'text', default: '', help: '起点列' },
      { key: 'targetCol', label: '目标列', type: 'text', default: '', help: '终点列' },
      { key: 'valueCol', label: '权重列(可选)', type: 'text', default: '', help: '留空按出现次数' },
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_graph',
    label: '网络示意图',
    category: 'visualize',
    description: '关系网络图(力导向布局):按源列→目标列构建边。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [],
    params: [
      { key: 'sourceCol', label: '源列', type: 'text', default: '', help: '起点列' },
      { key: 'targetCol', label: '目标列', type: 'text', default: '', help: '终点列' },
      { key: 'valueCol', label: '权重列(可选)', type: 'text', default: '', help: '留空按出现次数' },
      { key: 'title', label: '图表标题', type: 'text', default: '' },
    ],
    isViewer: true,
  },
  {
    id: 'viz_principled',
    label: '原理化输出',
    category: 'visualize',
    description: '原理化模式:接收点/线/面(均可多路连接)、分布与坐标系,所有图元缩放至互相垂直的坐标轴盒内部,预览窗与坐标系尺寸等比例。',
    inputs: [
      { id: 'in0', name: '点(散点·可多连)', type: 'scatter', multi: true },
      { id: 'in1', name: '线(曲线·可多连)', type: 'series', multi: true },
      { id: 'in2', name: '面(网格·可多连)', type: 'mesh', multi: true },
      s('in3', '分布', 'distribution'),
      s('in4', '坐标系', 'axes'),
    ],
    outputs: [],
    params: [
      { key: 'colorPreset', label: '颜色预设', type: 'select', default: 'paper', options: [
        { value: 'paper', label: '论文白(亮色)' },
        { value: 'custom', label: '自定义(使用下方颜色)' },
        { value: 'tech', label: '暗色科技' },
        { value: 'ocean', label: '海洋蓝' },
        { value: 'sunset', label: '落日橙' },
        { value: 'forest', label: '森林绿' },
        { value: 'neon', label: '霓虹紫' },
        { value: 'gray', label: '灰度' },
      ] },
      { key: 'axisColor', label: '坐标轴颜色(统一单色)', type: 'color', default: '#333333' },
      { key: 'wireframe', label: '线框模式(面)', type: 'boolean', default: false },
      { key: 'fillFaces', label: '填充面', type: 'boolean', default: true },
      { key: 'faceOpacity', label: '面透明度', type: 'range', default: 0.85, min: 0.05, max: 1, step: 0.05 },
      { key: 'rotX', label: '旋转 X', type: 'range', default: -20, min: -180, max: 180, step: 1 },
      { key: 'rotY', label: '旋转 Y', type: 'range', default: 25, min: -180, max: 180, step: 1 },
      { key: 'faceColor', label: '面颜色', type: 'color', default: '#2ca02c' },
      { key: 'distColor', label: '分布颜色', type: 'color', default: '#9467bd' },
      { key: 'bgColor', label: '背景色', type: 'color', default: '#ffffff' },
    ],
    isViewer: true,
  },
  {
    id: 'data_output',
    label: '数据输出',
    category: 'visualize',
    description: '输出节点:显示传入表格数据的预览(列名 + 前若干行),便于检查流水线中间结果。',
    inputs: [s('in0', '表格', 'table')],
    outputs: [],
    params: [
      { key: 'maxRows', label: '预览行数', type: 'number', default: 8, step: 1, min: 1, max: 50 },
    ],
    isViewer: true,
  },
];

const configMap = new Map(nodeConfigs.map((c) => [c.id, c]));

export function getConfig(id: string): NodeConfig | undefined {
  return configMap.get(id);
}

export function nodesByCategory(cat: (typeof nodeConfigs)[number]['category']) {
  return nodeConfigs.filter((c) => c.category === cat);
}
